sudo: false
language: python
cache:
  - pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox codecov
before_script:
  - echo ${GOOGLE_APPLICATION_CREDENTIALS} | base64 -d > credential.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credential.json
script:
  - tox
after_success:
  - codecov
